zwzone/ft_transcendence

- frontend/app.js
- frontend/router/router.js
This pull request resolves #11
> PR for issue #11

- frontend/app.js
- frontend/index.html
- frontend/pages/NotfoundPage.js
> PR for issue #9

- backend/apiapp/admin.py
- backend/apiapp/apps.py
- backend/apiapp/models.py
- backend/apiapp/serializers.py
- backend/apiapp/tests.py
- backend/apiapp/urls.py
- backend/apiapp/views.py
- backend/authenticationapp/urls.py
- backend/authenticationapp/views.py
- backend/core/settings.py
- backend/core/urls.py
- backend/requirements.txt
This pull request will resolve #18
> PR for issue #18

- frontend/app.js
- frontend/components/TournamentMatchCard.js
- frontend/components/TournamentPlayerCard.js
- frontend/css/LoginPage.css
- frontend/css/Navbar.css
- frontend/css/TournamentPage.css
- frontend/css/style.css
- frontend/index.html
This pull request will resolve #5
> PF for issue #5

- services/player/api/models.py
- services/player/api/serializers.py
- services/player/api/urls.py
- services/player/api/views.py
This pull request wil resolve #57
> PR for issue #57

- services/authentication/api/middleware.py
- services/authentication/api/service.py
- services/authentication/api/settings.py
- services/authentication/api/urls.py
- services/authentication/api/views.py
- services/authentication/requirements.txt
Added the "logout/" & "is_loged_in/" endpoints
> PR for issue #61

- client/css/Navbar.css
- client/css/ProfilePage.css
- client/css/SettingPage.css
- client/css/style.css
- client/index.html
This pull request will resolve #84
> PR for issue #84

- client/components/Navbar.js
- client/css/Navbar.css
- client/router/router.js
- client/utilities/fetching.js
- services/authentication/api/endpoints.py
> PR for issue #93

- README.md
> PR for issue #98

- services/authentication/api/endpoints.py
- services/authentication/api/guard.py
- services/authentication/api/middleware.py
- services/authentication/api/service.py
- services/authentication/api/views.py
- services/player/api/models.py
- services/player/api/views.py
> PR for issue #77

- Makefile
- client/Dockerfile
- client/Dockerfile.dev
- client/conf/nginx.conf
- services/authentication/Dockerfile
- services/authentication/Dockerfile.dev
- services/authentication/requirements.txt
- services/authentication/tools/microservice-run.sh
- services/player/Dockerfile
- services/player/Dockerfile.dev
- services/player/requirements.txt
- services/player/tools/microservice-run.sh
Set Daphne.ASGI for backend microservices in the developement and deployment, automate re developement, deploymenet of microservices and reseting data-base in makefile and fix nginx config file.
**Deploy microservices as containers to Docker :**
- **_Conf_**
- _**FIX:**_
- #101
- **_Deployment_**
-  #102
> FEAT: Daphne server for backend microservices

- services/authentication/api/service.py
- services/authentication/api/views.py
- services/player/api/decorators.py
- services/player/api/endpoints.py
- services/player/api/views.py
> PR for issue #105

- .gitignore
- services/authentication/api/endpoints.py
- services/authentication/api/settings.py
- services/player/api/decorators.py
- services/player/api/endpoints.py
- services/player/api/settings.py
- services/player/api/urls.py
- services/player/api/views.py
> FEAT: Add  Avatar POST

- client/app.js
- client/css/ProfilePage.css
- client/index.html
- client/pages/ProfilePage.js
- client/pages/SettingPage.js
- client/pong/pong.js
- client/router/router.js
- services/authentication/api/settings.py
- services/authentication/api/views.py
- services/player/api/settings.py
> FEAT: make the hostname our system dynamic

- client/pong/pong.js
- services/matchmaking/api/asgi.py
- services/matchmaking/api/settings.py
- services/matchmaking/requirements.txt
- services/pong/api/asgi.py
- services/pong/api/settings.py
- services/pong/requirements.txt
- adding requirement.txt files for matchmaking and pong
- resolve #119
> FEAT: websocket secure in matchmaking and pong

- services/player/api/endpoints.py
- services/player/api/views.py
Setup friendship model and Add all needed endpoints.
> FEAT: Add friendship system.

- services/authentication/api/service.py
- services/authentication/api/views.py
- services/player/api/views.py
> FIX: add authority to JWT payload

- client/utilities/pong.js
- services/pong/api/consumers.py
- services/pong/api/settings.py
> FEAT: optimization and styling pong game

- client/utilities/pong.js
- services/matchmaking/api/asgi.py
- services/matchmaking/api/consumers.py
- services/matchmaking/api/middleware.py
- services/matchmaking/api/settings.py
- services/matchmaking/requirements.txt
- services/pong/api/asgi.py
- services/pong/api/middleware.py
- services/pong/api/settings.py
- services/pong/requirements.txt
> FEAT: adding middlware to matchmaking and pong apps

- docker-compose.dev.yaml
- docker-compose.yaml
- services/postgres/Dockerfile
- services/postgres/conf/postgresql.conf
- services/postgres/tools/microservice-run.sh
This pull request will add the postgres and pgadmin containers using only official images currently.
- **_Deployment_** &  **_Development_**
- **_FEAT:_**
-  resolve  #143
> Adding the Postgres and pgadmin containers

- client/components/PlayCard.js
- client/css/GamePage.css
- client/css/HomePage.css
- client/css/style.css
- client/index.html
- client/pages/GamePage.js
- client/utilities/pongCoop.js
- client/utilities/pongFour.js
- client/utilities/pongTwo.js
> FEAT: link buttons of playing with backend

- services/authentication/api/service.py
- services/authentication/api/views.py
- services/tournament/api/models.py
- services/tournament/api/serializers.py
- services/tournament/api/settings.py
- services/tournament/api/urls.py
- services/tournament/api/views.py
- services/tournament/requirements.txt
> FIX:  fix issues with tournament app

- client/app.js
- client/components/FriendCard.js
- client/components/FriendCardPopup.js
- client/components/FriendsList.js
- client/components/MatchCard.js
- client/components/MatchHistory.js
- client/components/PlayerCard.js
- client/components/SearchList.js
- client/conf/nginx.conf
- client/css/ProfilePage.css
- client/index.html
- client/pages/ProfilePage.js
- client/pages/SettingPage.js
- client/pages/TournamentPage.js
- services/authentication/api/models.py
- services/matchmaking/api/models.py
- services/player/api/models.py
- services/pong/api/models.py
- services/tournament/api/models.py
- services/tournament/api/views.py
> FEAT: setup the match history in Frontend

- client/app.js
- client/components/TwofaInput.js
- client/index.html
- client/pages/ProfilePage.js
- client/router/router.js
- client/utilities/pongFour.js
- services/authentication/api/service.py
- services/authentication/api/views.py
- services/matchmaking/api/middleware.py
- services/player/api/decorators.py
- services/pong/api/middleware.py
- services/tournament/api/decorators.py
> BUG: fixing two factor auth frontend and backend

- client/router/router.js
- client/utilities/pongFour.js
- client/utilities/pongTwo.js
- services/pong/api/consumers.py
> FEAT: storing match history in db

- client/conf/nginx.conf
- client/css/components/FriendCard.css
- client/index.html
- client/js/components/FriendCard.js
- client/js/components/FriendsList.js
- client/js/components/SearchList.js
- client/js/utilities/pongFour.js
- client/js/utilities/pongTwo.js
- client/js/utilities/router.js
- services/authentication/api/asgi.py
- services/authentication/api/consumers.py
- services/authentication/api/endpoints.py
- services/authentication/api/middleware.py
- services/authentication/api/models.py
- services/authentication/api/routing.py
- services/authentication/api/settings.py
- services/authentication/api/views.py
- services/authentication/requirements.txt
- services/matchmaking/api/models.py
- services/player/api/models.py
- services/pong/api/consumers.py
- services/pong/api/models.py
- services/tournament/api/models.py
> FEAT: changing player status using websockets and coloring paddles
